export const oracleDiagnosticCodes = [
  'invalid-input',
  'invalid-utf8',
  'byte-order-mark-present',
  'no-entries',
  'unterminated-fenced-region',
  'missing-section',
  'duplicate-section',
  'missing-identifier',
  'identifier-grammar-violation',
  'identifier-heading-mismatch',
  'malformed-date',
  'malformed-status',
  'missing-subject',
  'duplicate-entry-identifier',
  'missing-declaration-block',
  'unterminated-declaration-block',
  'nested-declaration-block',
  'extraneous-declaration-content',
  'empty-declaration-block',
  'declaration-grammar-violation',
  'declaration-subject-grammar-violation',
  'unsupported-lifecycle-form',
  'relation-target-grammar-violation',
  'unsupported-lifecycle-status',
  'unsupported-relation-kind',
  'degenerate-segmentation',
  'duplicate-declaration-subject',
  'malformed-scope-key',
  'missing-scope-description',
  'residual-scope-description',
  'duplicate-scope-key',
  'incomplete-segmentation',
  'status-relation-mismatch',
  'declarant-not-effective',
  'self-referential-declaration',
  'cyclic-declaration-authority',
  'absent-declaration-subject',
  'generic-rule-conflict',
  'status-binding-mismatch',
  'duplicate-declaration',
  'absent-relation-target',
  'self-referential-relation',
  'cyclic-lifecycle-relation',
  'unresolved-lifecycle',
  'malformed-capture-instant',
  'malformed-attribution',
] as const;

export const oracleDiagnosticMetadata = Object.freeze({
  'invalid-input': ['SourceIntegrity', 0],
  'invalid-utf8': ['SourceIntegrity', 0],
  'byte-order-mark-present': ['SourceIntegrity', 0],
  'no-entries': ['EntryStructure', 1],
  'unterminated-fenced-region': ['EntryStructure', 1],
  'missing-section': ['EntryStructure', 1],
  'duplicate-section': ['EntryStructure', 1],
  'missing-identifier': ['EntryStructure', 1],
  'identifier-grammar-violation': ['EntryStructure', 1],
  'identifier-heading-mismatch': ['EntryStructure', 1],
  'malformed-date': ['EntryStructure', 1],
  'malformed-status': ['EntryStructure', 1],
  'missing-subject': ['EntryStructure', 1],
  'duplicate-entry-identifier': ['EntryStructure', 1],
  'missing-declaration-block': ['DeclarationGrammar', 2],
  'unterminated-declaration-block': ['DeclarationGrammar', 2],
  'nested-declaration-block': ['DeclarationGrammar', 2],
  'extraneous-declaration-content': ['DeclarationGrammar', 2],
  'empty-declaration-block': ['DeclarationGrammar', 2],
  'declaration-grammar-violation': ['DeclarationGrammar', 2],
  'declaration-subject-grammar-violation': ['DeclarationGrammar', 2],
  'unsupported-lifecycle-form': ['DeclarationGrammar', 2],
  'relation-target-grammar-violation': ['DeclarationGrammar', 2],
  'unsupported-lifecycle-status': ['DeclarationGrammar', 2],
  'unsupported-relation-kind': ['DeclarationGrammar', 2],
  'degenerate-segmentation': ['DeclarationGrammar', 2],
  'duplicate-declaration-subject': ['DeclarationGrammar', 2],
  'malformed-scope-key': ['DeclarationGrammar', 2],
  'missing-scope-description': ['DeclarationGrammar', 2],
  'residual-scope-description': ['DeclarationGrammar', 2],
  'duplicate-scope-key': ['DeclarationGrammar', 2],
  'incomplete-segmentation': ['DeclarationGrammar', 2],
  'status-relation-mismatch': ['DeclarationGrammar', 2],
  'declarant-not-effective': ['DeclarantAuthority', 3],
  'self-referential-declaration': ['DeclarantAuthority', 3],
  'cyclic-declaration-authority': ['DeclarantAuthority', 3],
  'absent-declaration-subject': ['DeclarationBinding', 4],
  'generic-rule-conflict': ['DeclarationBinding', 4],
  'status-binding-mismatch': ['DeclarationBinding', 4],
  'duplicate-declaration': ['DeclarationBinding', 4],
  'absent-relation-target': ['LifecycleGraph', 5],
  'self-referential-relation': ['LifecycleGraph', 5],
  'cyclic-lifecycle-relation': ['LifecycleGraph', 5],
  'unresolved-lifecycle': ['Resolution', 6],
  'malformed-capture-instant': ['Envelope', 8],
  'malformed-attribution': ['Envelope', 8],
} as const);

